---
- name: Verify the mirror registry responds to API call
  uri:
    url: "https://{{ ansible_fqdn }}:{{ mirror_registry_port }}/v2/_catalog"
    validate_certs: "{{ mirror_registry_validate_certs }}"
    url_username: "{{ mirror_registry_user }}"
    url_password: "{{ mirror_registry_password }}"
    status_code: 200
